name: release

on:
    push:
        branches: [ $default-branch ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Checkout submodules
              run: git submodule update --init --recursive

            - name: Install FPGA toolchain
              uses: YosysHQ/setup-oss-cad-suite@v1

            - name: Install RISC-V toolchain
              run: |
                wget https://github.com/xpack-dev-tools/riscv-none-embed-gcc-xpack/releases/download/v10.1.0-1.1/xpack-riscv-none-embed-gcc-10.1.0-1.1-linux-x64.tar.gz
                tar -xf xpack-riscv-none-embed-gcc-10.1.0-1.1-linux-x64.tar.gz
                rm xpack-riscv-none-embed-gcc-10.1.0-1.1-linux-x64.tar.gz
                echo "$(pwd)/xpack-riscv-none-embed-gcc-10.1.0-1.1/bin" >> $GITHUB_PATH

            - name: Run gateware build
              run: |
                ./dist.sh
                TAG=$(cat build/tag.txt)
                echo "TAG=$TAG" >> $GITHUB_ENV

            - name: Build artifact upload
              uses: actions/upload-artifact@v2
              with:
                name: muacm-build
                path: |
                  build/muacm-*.ilang.bz2
                  build/muacm-*.tar.bz2

            - name: Release (as draft)
              uses: softprops/action-gh-release@v1
              with:
                name: Release ${{ env.TAG }}
                tag_name: ${{ env.TAG }}
                draft: true
                files: |
                  build/muacm-*.ilang.bz2
                  build/muacm-*.tar.bz2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
